version: '3.9'
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5430:5432"
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d
