version: '3.9'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres-monolith
    volumes:
      - postgres_data_23_08_23:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
volumes:
  postgres_data_23_08_23:
    name: postgres_data_23_08_23
