version: '3.9'
services:
  postgres:
    container_name: postgres-monolith
    image: postgres:15.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
